import { STYLES, DEFAULT_STYLE } from "./codes";
import type { GroupId, SlotDef } from "./types";

const armorVars = STYLES.map((s) => ({ id: s.id, name: s.id }));

const WEAPON_VARS = [
  { id: "none", name: "None" },
  { id: "rifle", name: "Beam Rifle" },
  { id: "longrifle", name: "Long Rifle" },
  { id: "machinegun", name: "Machine Gun" },
  { id: "cannon", name: "Cannon" },
  { id: "shotgun", name: "Shotgun" },
  { id: "sniper", name: "Sniper" },
  { id: "pistol", name: "Pistol" },
  { id: "smg", name: "SMG" },
  { id: "bazooka", name: "Bazooka" },
  { id: "vulcan", name: "Vulcan" },
  { id: "saber", name: "Beam Saber" },
  { id: "beamdagger", name: "Beam Dagger" },
  { id: "naginata", name: "Beam Naginata" },
  { id: "twin", name: "Twin Beam" },
  { id: "dagger", name: "Dagger" },
  { id: "longsword", name: "Longsword" },
  { id: "axe", name: "Axe" },
  { id: "hammer", name: "Hammer" },
  { id: "spear", name: "Spear" },
  { id: "mace", name: "Mace" },
];

const SHIELD_VARS = [
  { id: "none", name: "None" },
  { id: "kite", name: "Kite" },
  { id: "round", name: "Round" },
  { id: "tower", name: "Tower" },
  { id: "buckler", name: "Buckler" },
  { id: "heater", name: "Heater" },
  { id: "scutum", name: "Scutum" },
  { id: "hex", name: "Hex" },
  { id: "penta", name: "Pentagon" },
  { id: "oval", name: "Oval" },
  { id: "delta", name: "Delta" },
  { id: "cross", name: "Cross" },
  { id: "spike", name: "Spiked" },
  { id: "wing", name: "Wing" },
  { id: "slab", name: "Slab" },
  { id: "dish", name: "Dish" },
  { id: "blade", name: "Blade" },
  { id: "lattice", name: "Lattice" },
  { id: "diamond", name: "Diamond" },
  { id: "capsule", name: "Capsule" },
  { id: "layer", name: "Layered" },
];

export const BEAM_MELEE = new Set(["saber", "beamdagger", "naginata", "twin"]);

export type ExtraCls = "M" | "W" | "A" | "G";

export const EXTRA_VARS: { id: string; name: string; cls?: ExtraCls }[] = [
  { id: "none", name: "None" },
  { id: "booster", name: "Booster", cls: "M" },
  { id: "twinboost", name: "Twin Booster", cls: "M" },
  { id: "container", name: "Container", cls: "M" },
  { id: "pod", name: "Pod", cls: "M" },
  { id: "propellant", name: "Propellant", cls: "M" },
  { id: "binderwing", name: "Binder Wing", cls: "M" },
  { id: "hardpoint", name: "Hardpoint", cls: "M" },
  { id: "droptank", name: "Drop Tank", cls: "M" },
  { id: "shieldbinder", name: "Shield Binder", cls: "M" },
  { id: "vernier", name: "Vernier", cls: "M" },
  { id: "packext", name: "Pack Ext", cls: "M" },
  { id: "skirtbinder", name: "Skirt Binder", cls: "M" },
  { id: "shoulderpod", name: "Shoulder Pod", cls: "M" },
  { id: "hipcontainer", name: "Hip Container", cls: "M" },
  { id: "thrusterring", name: "Thruster Ring", cls: "M" },
  { id: "conformaltank", name: "Conformal Tank", cls: "M" },
  { id: "twinwing", name: "Twin Wing", cls: "M" },
  { id: "radome", name: "Radome", cls: "M" },
  { id: "cooler", name: "Cooler", cls: "M" },
  { id: "stealthplate", name: "Stealth Plate", cls: "M" },
  { id: "deltaWing", name: "Delta Wing", cls: "M" },
  { id: "sweptWing", name: "Swept Wing", cls: "M" },
  { id: "canardWing", name: "Canard Wing", cls: "M" },
  { id: "stubWing", name: "Stub Wing", cls: "M" },
  { id: "scissorWing", name: "Scissor Wing", cls: "M" },
  { id: "shouldercannon", name: "Shoulder Cannon", cls: "W" },
  { id: "missilepod", name: "Missile Pod", cls: "W" },
  { id: "saberrack", name: "Saber Rack", cls: "W" },
  { id: "grenaderack", name: "Grenade Rack", cls: "W" },
  { id: "longcannon", name: "Long Cannon", cls: "W" },
  { id: "gatling", name: "Gatling", cls: "W" },
  { id: "railgun", name: "Railgun", cls: "W" },
  { id: "shotcannon", name: "Scatter Cannon", cls: "W" },
  { id: "heathawk", name: "Heat Hawk", cls: "W" },
  { id: "lancepod", name: "Lance", cls: "W" },
  { id: "megacannon", name: "Mega Cannon", cls: "W" },
  { id: "bitrack", name: "Bit Rack", cls: "W" },
  { id: "armcannon", name: "Arm Cannon", cls: "W" },
  { id: "chestvulcan", name: "Chest Vulcan", cls: "W" },
  { id: "armgatling", name: "Arm Gatling", cls: "W" },
  { id: "rocket", name: "Rocket", cls: "W" },
  { id: "twinsaber", name: "Twin Saber", cls: "W" },
  { id: "shieldcannon", name: "Shield Cannon", cls: "W" },
  { id: "sniper", name: "Sniper", cls: "W" },
  { id: "cluster", name: "Cluster", cls: "W" },
  { id: "bladeantenna", name: "Blade Antenna", cls: "A" },
  { id: "twinantenna", name: "Twin Antenna", cls: "A" },
  { id: "glowfin", name: "Glow Fin", cls: "A" },
  { id: "crestplate", name: "Crest", cls: "A" },
  { id: "cameraeye", name: "Camera Eye", cls: "A" },
  { id: "sensorhorn", name: "Sensor Horn", cls: "A" },
  { id: "headvulcan", name: "Head Vulcan", cls: "A" },
  { id: "bitunit", name: "Bit Unit", cls: "A" },
  { id: "glowstrip", name: "Glow Strip", cls: "A" },
  { id: "finblade", name: "Fin Blade", cls: "A" },
  { id: "chinspike", name: "Chin Spike", cls: "A" },
  { id: "cheekblade", name: "Cheek Blade", cls: "A" },
  { id: "headcamera", name: "Head Camera", cls: "A" },
  { id: "commantenna", name: "Comm Antenna", cls: "A" },
  { id: "haloring", name: "Halo Ring", cls: "A" },
  { id: "sidespike", name: "Side Spike", cls: "A" },
  { id: "coregem", name: "Core Gem", cls: "A" },
  { id: "tailstab", name: "Tail Stab", cls: "A" },
  { id: "skirtspike", name: "Skirt Spike", cls: "A" },
  { id: "shoulderspike", name: "Shoulder Spike", cls: "A" },
  { id: "cube", name: "Cube", cls: "G" },
  { id: "cuboid", name: "Cuboid", cls: "G" },
  { id: "sphere", name: "Sphere", cls: "G" },
  { id: "cylinder", name: "Cylinder", cls: "G" },
  { id: "cone", name: "Cone", cls: "G" },
  { id: "torus", name: "Torus", cls: "G" },
  { id: "tetra", name: "Tetra", cls: "G" },
  { id: "octa", name: "Octa", cls: "G" },
  { id: "dodeca", name: "Dodeca", cls: "G" },
  { id: "icosa", name: "Icosa", cls: "G" },
  { id: "pyramid", name: "Pyramid", cls: "G" },
  { id: "prism", name: "Prism", cls: "G" },
  { id: "hexprism", name: "Hex Prism", cls: "G" },
  { id: "capsule", name: "Capsule", cls: "G" },
  { id: "disc", name: "Disc", cls: "G" },
  { id: "ring", name: "Ring", cls: "G" },
  { id: "wedge", name: "Wedge", cls: "G" },
  { id: "cross", name: "Cross", cls: "G" },
  { id: "hemisphere", name: "Hemisphere", cls: "G" },
  { id: "knot", name: "Knot", cls: "G" },
];

export const WING_IDS = ["deltaWing", "sweptWing", "canardWing", "stubWing", "scissorWing"];

export const MOD_IDS = EXTRA_VARS.filter((v) => v.cls === "M").map((v) => v.id);
export const WPN_IDS = EXTRA_VARS.filter((v) => v.cls === "W").map((v) => v.id);
export const ACC_IDS = EXTRA_VARS.filter((v) => v.cls === "A").map((v) => v.id);

export const EXTRA_LEGACY: Record<string, string> = {
  funnel: "bitunit",
  booster: "booster",
  missile: "missilepod",
  cannon: "shouldercannon",
  binder: "binderwing",
  sensor: "bladeantenna",
  rack: "saberrack",
  "M-01": "booster",
  "M-02": "twinboost",
  "M-03": "container",
  "M-04": "pod",
  "M-05": "propellant",
  "M-06": "binderwing",
  "M-07": "hardpoint",
  "M-08": "droptank",
  "M-09": "shieldbinder",
  "M-10": "vernier",
  "M-11": "packext",
  "M-12": "skirtbinder",
  "M-13": "shoulderpod",
  "M-14": "hipcontainer",
  "M-15": "thrusterring",
  "M-16": "conformaltank",
  "M-17": "twinwing",
  "M-18": "radome",
  "M-19": "cooler",
  "M-20": "stealthplate",
  "W-01": "shouldercannon",
  "W-02": "missilepod",
  "W-03": "saberrack",
  "W-04": "grenaderack",
  "W-05": "longcannon",
  "W-06": "gatling",
  "W-07": "railgun",
  "W-08": "shotcannon",
  "W-09": "heathawk",
  "W-10": "lancepod",
  "W-11": "megacannon",
  "W-12": "bitrack",
  "W-13": "armcannon",
  "W-14": "chestvulcan",
  "W-15": "armgatling",
  "W-16": "rocket",
  "W-17": "twinsaber",
  "W-18": "shieldcannon",
  "W-19": "sniper",
  "W-20": "cluster",
  "A-01": "bladeantenna",
  "A-02": "twinantenna",
  "A-03": "glowfin",
  "A-04": "crestplate",
  "A-05": "cameraeye",
  "A-06": "sensorhorn",
  "A-07": "headvulcan",
  "A-08": "bitunit",
  "A-09": "glowstrip",
  "A-10": "finblade",
  "A-11": "chinspike",
  "A-12": "cheekblade",
  "A-13": "headcamera",
  "A-14": "commantenna",
  "A-15": "haloring",
  "A-16": "sidespike",
  "A-17": "coregem",
  "A-18": "tailstab",
  "A-19": "skirtspike",
  "A-20": "shoulderspike",
};

function S(
  id: string,
  group: SlotDef["group"],
  label: string,
  socket: SlotDef["socket"],
  extra: Partial<SlotDef> = {},
): SlotDef {
  return {
    id,
    group,
    label,
    socket,
    kind: "armor",
    defaultVariant: DEFAULT_STYLE,
    variants: armorVars,
    ...extra,
  };
}

export const SLOTS: SlotDef[] = [
  // head lowered 0.03 in Y — shorter visual neck over the new cervical column
  S("helm", "head", "Helm", [0, 1.79, 0]),
  S("visor", "head", "Visor", [0, 1.78, 0.065]),
  S("brow", "head", "Brow", [0, 1.84, 0.06]),
  S("eyeL", "head", "Eye L", [-0.048, 1.79, 0.07], { mirror: "eyeR" }),
  S("eyeR", "head", "Eye R", [0.048, 1.79, 0.07], { mirror: "eyeL" }),
  S("nose", "head", "Nose", [0, 1.76, 0.075]),
  S("mouth", "head", "Mouth", [0, 1.715, 0.065]),
  S("jaw", "head", "Jaw", [0, 1.66, 0.04]),
  S("earL", "head", "Ear L", [-0.115, 1.78, 0], { optional: true, mirror: "earR" }),
  S("earR", "head", "Ear R", [0.115, 1.78, 0], { optional: true, mirror: "earL" }),
  S("vfin", "head", "Crest", [0, 1.88, 0.04]),
  S("antennaL", "head", "Antenna L", [-0.08, 1.86, -0.01], {
    optional: true,
    mirror: "antennaR",
  }),
  S("antennaR", "head", "Antenna R", [0.08, 1.86, -0.01], {
    optional: true,
    mirror: "antennaL",
  }),
  S("cheekL", "head", "Cheek L", [-0.095, 1.73, 0.035], { mirror: "cheekR" }),
  S("cheekR", "head", "Cheek R", [0.095, 1.73, 0.035], { mirror: "cheekL" }),
  S("chin", "head", "Chin Guard", [0, 1.68, 0.065]),

  // collar is a low protective RIM around the cervical column (emitted by
  // chestCore); it sits down near the core, not up by the head
  S("collar", "torso", "Collar", [0, 1.58, 0.02]),
  S("chestCore", "torso", "Chest Core", [0, 1.44, 0.04]),
  S("chestR", "torso", "Chest R", [0.2, 1.4, 0.02], { mirror: "chestL" }),
  S("chestL", "torso", "Chest L", [-0.2, 1.4, 0.02], { mirror: "chestR" }),
  S("pecL", "torso", "Pec L", [-0.13, 1.46, 0.09], { mirror: "pecR" }),
  S("pecR", "torso", "Pec R", [0.13, 1.46, 0.09], { mirror: "pecL" }),
  S("cockpit", "torso", "Cockpit", [0, 1.40, 0.14]),
  S("abdomen", "torso", "Abdomen", [0, 1.22, 0.03]),

  S("pelvis", "waist", "Pelvis", [0, 1.06, 0]),
  S("skirtF", "waist", "Skirt F", [0, 1.02, 0.12]),
  S("skirtB", "waist", "Skirt B", [0, 1.02, -0.10]),
  S("skirtL", "waist", "Skirt L", [-0.16, 1.02, 0], { mirror: "skirtR" }),
  S("skirtR", "waist", "Skirt R", [0.16, 1.02, 0], { mirror: "skirtL" }),

  // arm groups: back down to track the lowered chest / collar
  S("shoulderR", "armR", "Shoulder R", [0.30, 1.46, 0], { mirror: "shoulderL" }),
  S("upperR", "armR", "Upper R", [0.30, 1.26, 0], { mirror: "upperL" }),
  S("elbowR", "armR", "Elbow R", [0.30, 1.08, 0], { mirror: "elbowL" }),
  S("forearmR", "armR", "Forearm R", [0.30, 0.90, 0], { mirror: "forearmL" }),
  S("vambraceR", "armR", "Vambrace R", [0.30, 0.88, 0.03], { mirror: "vambraceL" }),
  S("handR", "armR", "Hand R", [0.30, 0.72, 0], { mirror: "handL" }),

  S("shoulderL", "armL", "Shoulder L", [-0.30, 1.46, 0], { mirror: "shoulderR" }),
  S("upperL", "armL", "Upper L", [-0.30, 1.26, 0], { mirror: "upperR" }),
  S("elbowL", "armL", "Elbow L", [-0.30, 1.08, 0], { mirror: "elbowR" }),
  S("forearmL", "armL", "Forearm L", [-0.30, 0.90, 0], { mirror: "forearmR" }),
  S("vambraceL", "armL", "Vambrace L", [-0.30, 0.88, 0.03], { mirror: "vambraceR" }),
  S("handL", "armL", "Hand L", [-0.30, 0.72, 0], { mirror: "handR" }),

  S("hipR", "legR", "Hip R", [0.14, 0.98, 0], { mirror: "hipL" }),
  S("thighR", "legR", "Thigh R", [0.14, 0.76, 0], { mirror: "thighL" }),
  S("kneeR", "legR", "Knee R", [0.14, 0.50, 0.02], { mirror: "kneeL" }),
  S("shinR", "legR", "Shin R", [0.14, 0.28, 0.01], { mirror: "shinL" }),
  S("ankleR", "legR", "Ankle R", [0.14, 0.10, 0], { mirror: "ankleL" }),
  S("footR", "legR", "Foot R", [0.14, 0.04, 0.02], { mirror: "footL" }),

  S("hipL", "legL", "Hip L", [-0.14, 0.98, 0], { mirror: "hipR" }),
  S("thighL", "legL", "Thigh L", [-0.14, 0.76, 0], { mirror: "thighR" }),
  S("kneeL", "legL", "Knee L", [-0.14, 0.50, 0.02], { mirror: "kneeR" }),
  S("shinL", "legL", "Shin L", [-0.14, 0.28, 0.01], { mirror: "shinR" }),
  S("ankleL", "legL", "Ankle L", [-0.14, 0.10, 0], { mirror: "ankleR" }),
  S("footL", "legL", "Foot L", [-0.14, 0.04, 0.02], { mirror: "footR" }),

  S("pack", "back", "Pack Core", [0, 1.46, -0.16]),
  S("thrusterL", "back", "Thruster L", [-0.14, 1.42, -0.24], { mirror: "thrusterR" }),
  S("thrusterR", "back", "Thruster R", [0.14, 1.42, -0.24], { mirror: "thrusterL" }),
  S("binderL", "back", "Binder L", [-0.24, 1.50, -0.18], {
    optional: true,
    defaultVariant: STYLES[26]?.id ?? DEFAULT_STYLE,
    mirror: "binderR",
  }),
  S("binderR", "back", "Binder R", [0.24, 1.50, -0.18], {
    optional: true,
    defaultVariant: STYLES[26]?.id ?? DEFAULT_STYLE,
    mirror: "binderL",
  }),
  S("stabilizer", "back", "Stabilizer", [0, 1.28, -0.22], { optional: true }),

  {
    id: "weaponR",
    group: "weapon",
    label: "Weapon R",
    socket: [0.30, 0.74, 0],
    kind: "weapon",
    defaultVariant: "none",
    variants: WEAPON_VARS,
  },
  {
    id: "weaponL",
    group: "weapon",
    label: "Weapon L",
    socket: [-0.30, 0.74, 0],
    kind: "weapon",
    defaultVariant: "none",
    variants: WEAPON_VARS,
  },
  {
    id: "shield",
    group: "weapon",
    label: "Shield",
    socket: [-0.33, 0.92, 0.04],
    kind: "weapon",
    defaultVariant: "none",
    variants: SHIELD_VARS,
  },

  ...([
    ["extra1", "R Shoulder", [0.34, 1.56, -0.06] as SlotDef["socket"]],
    ["extra2", "L Shoulder", [-0.34, 1.56, -0.06] as SlotDef["socket"]],
    ["extra3", "R Hip", [0.20, 1.04, 0.10] as SlotDef["socket"]],
    ["extra4", "L Hip", [-0.20, 1.04, 0.10] as SlotDef["socket"]],
    ["extra5", "Head Rear", [0, 1.76, -0.16] as SlotDef["socket"]],
    ["extra6", "Waist Rear", [0, 1.14, -0.18] as SlotDef["socket"]],
    ["extra7", "Face Front", [0, 1.81, 0.12] as SlotDef["socket"]],
    ["extra8", "Chest", [0, 1.44, 0.18] as SlotDef["socket"]],
    ["extra9", "Forearm R", [0.35, 0.92, 0.05] as SlotDef["socket"]],
    ["extra10", "Forearm L", [-0.35, 0.92, 0.05] as SlotDef["socket"]],
  ] as const).map(([id, label, socket]) => ({
    id,
    group: "extra" as const,
    label,
    socket,
    kind: "extra" as const,
    optional: true,
    defaultVariant: "none",
    variants: EXTRA_VARS,
  })),
];

export const SLOT_BY_ID = Object.fromEntries(SLOTS.map((s) => [s.id, s]));

export const GROUP_ROOT: Record<GroupId, string> = {
  head: "helm",
  torso: "chestCore",
  waist: "pelvis",
  armR: "shoulderR",
  armL: "shoulderL",
  legR: "hipR",
  legL: "hipL",
  back: "pack",
  weapon: "weaponR",
  extra: "extra1",
};

export function isLeftSlot(id: string) {
  return /L$/.test(id) || id === "weaponL";
}

export function isVisorSlot(id: string) {
  return id === "visor" || id === "eyeL" || id === "eyeR";
}

export function variantLabel(slotId: string, variant: string): string {
  const def = SLOT_BY_ID[slotId];
  return def?.variants.find((v) => v.id === variant)?.name ?? variant;
}
